# Generated by Django 4.0.2 on 2022-03-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_user_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
